services:
  api1: &api
    image: ghcr.io/viniciusdsandrade/rinha-de-backend-2026:submission-rust-manual-oldrepair-66a7668
    platform: linux/amd64
    environment:
      UNIX_SOCKET_PATH: /sockets/api1.sock
      IVF_FAST_NPROBE: "1"
      IVF_FULL_NPROBE: "1"
      IVF_BOUNDARY_FULL: "true"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN_FRAUDS: "1"
      IVF_REPAIR_MAX_FRAUDS: "4"
    networks:
      - backend
    volumes:
      - sockets:/sockets
    deploy:
      resources:
        limits:
          cpus: "0.42"
          memory: "160MB"

  api2:
    <<: *api
    environment:
      UNIX_SOCKET_PATH: /sockets/api2.sock
      IVF_FAST_NPROBE: "1"
      IVF_FULL_NPROBE: "1"
      IVF_BOUNDARY_FULL: "true"
      IVF_BBOX_REPAIR: "true"
      IVF_REPAIR_MIN_FRAUDS: "1"
      IVF_REPAIR_MAX_FRAUDS: "4"

  lb:
    image: nginx:1.27-alpine
    platform: linux/amd64
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
    volumes:
      - sockets:/sockets
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      resources:
        limits:
          cpus: "0.16"
          memory: "30MB"

networks:
  backend:
    driver: bridge

volumes:
  sockets:
